### PR TITLE
Issues and testId patterns can now be defined in pom file

### PR DESCRIPTION
**Pull request by piociek**
I'd like to configure Issue Tracker and TestCaseId in Allure so that they numbers in reports are converted into valid URLs, by changing POM file so that I don't need to ask CI/CD teams to change command line params.

With this change we may do it like:
```
<configuration>
    <testIdPattern>http://testcases.com/test/%s</testIdPattern>
    <issuesPattern>http://issues.com/id/%s</issuesPattern>
</configuration>
```

### CODE REVIEW

**Comment by vania-pooh** [comment]
@baev seems to be a good idea. Any ideas against merging this?

**Comment by ctapobep** [comment]
This will probably resolve #18 as well since it's not that important whether we put the link into POM or into the properties file.

**Comment by baev** [comment]
@piociek sorry for the delay. Could you please write a test for such feature? An example of integration test: https://github.com/allure-framework/allure-maven-plugin/tree/master/src/it/report-sample-1.4.16

**Comment by baev** [comment]
@piociek there is an example of the test https://github.com/allure-framework/allure-maven-plugin/pull/22

**Comment by baev** [comment]
BTW I fix #18 and this one via https://github.com/allure-framework/allure-maven-plugin/pull/23

Thanks for the contribution! I'll release 2.5 ASAP and you can try

**Pull request closed without merging**
